car:
  WHEEL_RADIUS: 0.35  # m
  DEMULTIPLICATION: 11  # -
  WEIGHT: 1800  # kg
  GRAVITY: 9.81  # m/s^2
  AUXILIARY_POWER: 300  # W
  THERMAL_ENGINE_PRESENCE: true

battery:
  N_CELLS: 84  # -
  CD_INITIAL_SOC: 0.95  # -
  CS_INITIAL_SOC: 0.22  # -
  RANGE_SOC: 0.002  # -
  TARGET_SOC: 0.22  # -
  CELL_CAPACITY: 40  # Ah

drag:
  F0: 150  # N
  F1: 0.0  # = 0.0 * 3.6 N/mps
  F2: 0.618192  # = 0.0477 * 3.6**2 N/mps^2

engine:
  TH_ENGINE_MINIMAL_TIME_ON: 50  # s
  EMOTOR2_OPTIMAL_RPM: 3000  # RPM
  EMOTOR2_OPTIMAL_CME: 130  # Nm
  EL2_efficiency: 0.9  # [-]

cycle:
  road_name: "WLTP"  # -
  number_of_CD_cycles: 6  # -
  number_of_CS_cycles: 1  # -

output:
  SAVE_RESULTS: true  # -
  PLOT_RESULTS: true  # -

logger:
  LOG_LEVEL: "DEBUG"  # -
  LOG_FILE: "main.log"  # -
  LOG_FORMAT: "%(levelname)s - %(message)s"  # %(asctime)s - %(name)s - 




